### ISSUE TITLE
As a User, I want to be able to add flair to my profile.

### ISSUE THREAD

**Issue by pvanarkel** [pvanarkel/discord-jeeves#18]
Users want to be able to add flair to their profile in the form of roles. These could be flair like pronouns, but also things like 'Contact me for crafting questions' of 'You can send me a DM'.

A User sent the following example from another server they're in.

<img width="319" alt="Schermafbeelding_2021-07-12_om_16 35 05" src="https://user-images.githubusercontent.com/8160843/125451709-fe0fa317-b5a2-4a3e-97c7-0d176a58e89b.png">
<img width="355" alt="Schermafbeelding_2021-07-12_om_16 34 53" src="https://user-images.githubusercontent.com/8160843/125451736-d28e317d-9214-4311-b6f1-64b4b0e9e6c1.png">
<img width="277" alt="Schermafbeelding_2021-07-12_om_16 38 24" src="https://user-images.githubusercontent.com/8160843/125451771-f68b4aca-0499-43ff-8f8e-348956441959.png">

This is very easily done by adding the roleadd-functionality to Jeeves (which was already partially implemented due to the LongTimeListener shortlarp), I made a quick mockup of how this would look on our end (used #, but these "role-categories" could be named anything we would want them to be named.

![Schermafbeelding 2021-07-13 141707](https://user-images.githubusercontent.com/8160843/125451985-01593909-1f8f-4889-8745-03a17da1c8be.png)

Note: Implementing this would solve a few suggestions that were coined by users in the idea-box;
- gender pronouns
- 'Are you open for DMs?'
- 'Yes, I want to be able to see channels with mature discussions'

**Comment by NieskeL** [comment]
Cool feature. I have seen this on a few different Discords, and it seems to work pretty well. 
Gender is always a good one.

**Comment by YvonVuijk** [comment]
I approve on all 3 examples! I can ask Eva for a list of pronoun options if requested.

**Comment by IreneSchuit** [comment]
Looks good, one issue I have with the icon for 'other gender' is that baldness is at least regularly, not a choice and I feel uncomfortable about it. But the set up looks good!

**Comment by pvanarkel** [comment]
> 
> 
> Looks good, one issue I have with the icon for 'other gender' is that baldness is at least regularly, not a choice and I feel uncomfortable about it. But the set up looks good!

The emoji are not what we're going to be using per sé; they're an example from the user that coined the idea. When I start the implementation, I'll confer with the mod-team for appropriate emoji :)

**Comment by pvanarkel** [comment]
> 
> 
> I approve on all 3 examples! I can ask Eva for a list of pronoun options if requested.

Yes please, in dutch if possible :)

**Comment by pvanarkel** [comment]
Questions to implement at this stage: 

- [ ] Gender pronouns
- [ ] Open for DMs
- [ ] Mature discussions

**Comment by YvonVuijk** [comment]
Lijst met pronouns om te implementeren, opgesteld in samenwerking met Eva:

- hij/hem
- zij/haar
- hen/hun
- die/hun
- die/diens
- iedere/alle

**Comment by pvanarkel** [comment]
Feedback from mods about the 'Open to discussions' role:

- `DM: ja`
- `DM: nee`

**Comment by YvonVuijk** [comment]
Is it possible for users to remove flairs?

**Comment by pvanarkel** [comment]
> 

Yes! Users can click an emoji to get a role and can click it again to remove that role. There will also be an option to reset the flair roles entirely.

![afbeelding](https://user-images.githubusercontent.com/8160843/223727459-a8c119af-0ebf-4155-9702-6906794c62f7.png)

Both actions in this log are user-initiated :)
